# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule: 
   - cron: "@weekly"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - run: npm install
    - run: npx npm-check-updates -u
    - run: npm install
    - run: npm update
    - run: npm audit fix --force
    - run: npm run lint
    - run: npm run build
    - run: npm test
    - run: git commit -am "update"
    - run: git push origin master
